// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WasteGlass.Api.Data;

#nullable disable

namespace WasteGlass.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WasteGlass.Api.Models.CollectionRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ClearKg")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime>("CollectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ColouredKg")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsSynced")
                        .HasColumnType("boolean");

                    b.Property<string>("LocalRecordId")
                        .HasColumnType("text");

                    b.Property<int>("SupplierId")
                        .HasColumnType("integer");

                    b.Property<int>("TripId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.HasIndex("TripId");

                    b.ToTable("collection_records", (string)null);
                });

            modelBuilder.Entity("WasteGlass.Api.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BarcodeValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ExpectedClearKg")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("ExpectedColouredKg")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SupplierCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BarcodeValue")
                        .IsUnique();

                    b.HasIndex("SupplierCode")
                        .IsUnique();

                    b.ToTable("suppliers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Pettah, Colombo",
                            BarcodeValue = "SUP001",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExpectedClearKg = 40m,
                            ExpectedColouredKg = 20m,
                            Latitude = 6.9366000000000003,
                            Longitude = 79.849699999999999,
                            Name = "Pettah Bottle Supplier",
                            SupplierCode = "SUP001"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Fort, Colombo",
                            BarcodeValue = "SUP002",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExpectedClearKg = 35m,
                            ExpectedColouredKg = 25m,
                            Latitude = 6.9344000000000001,
                            Longitude = 79.842799999999997,
                            Name = "Fort Hotel Waste Point",
                            SupplierCode = "SUP002"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Maradana, Colombo",
                            BarcodeValue = "SUP003",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExpectedClearKg = 50m,
                            ExpectedColouredKg = 30m,
                            Latitude = 6.9259000000000004,
                            Longitude = 79.864800000000002,
                            Name = "Maradana Glass Store",
                            SupplierCode = "SUP003"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Borella, Colombo",
                            BarcodeValue = "SUP004",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExpectedClearKg = 45m,
                            ExpectedColouredKg = 35m,
                            Latitude = 6.9146999999999998,
                            Longitude = 79.877799999999993,
                            Name = "Borella Recycling Supplier",
                            SupplierCode = "SUP004"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Narahenpita, Colombo",
                            BarcodeValue = "SUP005",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExpectedClearKg = 55m,
                            ExpectedColouredKg = 25m,
                            Latitude = 6.8897000000000004,
                            Longitude = 79.879400000000004,
                            Name = "Narahenpita Bottle Collection",
                            SupplierCode = "SUP005"
                        });
                });

            modelBuilder.Entity("WasteGlass.Api.Models.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("StartLatitude")
                        .HasColumnType("double precision");

                    b.Property<double>("StartLongitude")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("TotalDistanceKm")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("TripDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("trips", (string)null);
                });

            modelBuilder.Entity("WasteGlass.Api.Models.TripStop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("DistanceFromPreviousKm")
                        .HasColumnType("double precision");

                    b.Property<int>("SequenceNo")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SupplierId")
                        .HasColumnType("integer");

                    b.Property<int>("TripId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.HasIndex("TripId");

                    b.ToTable("trip_stops", (string)null);
                });

            modelBuilder.Entity("WasteGlass.Api.Models.CollectionRecord", b =>
                {
                    b.HasOne("WasteGlass.Api.Models.Supplier", "Supplier")
                        .WithMany("CollectionRecords")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WasteGlass.Api.Models.Trip", "Trip")
                        .WithMany("CollectionRecords")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("WasteGlass.Api.Models.TripStop", b =>
                {
                    b.HasOne("WasteGlass.Api.Models.Supplier", "Supplier")
                        .WithMany("TripStops")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WasteGlass.Api.Models.Trip", "Trip")
                        .WithMany("Stops")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("WasteGlass.Api.Models.Supplier", b =>
                {
                    b.Navigation("CollectionRecords");

                    b.Navigation("TripStops");
                });

            modelBuilder.Entity("WasteGlass.Api.Models.Trip", b =>
                {
                    b.Navigation("CollectionRecords");

                    b.Navigation("Stops");
                });
#pragma warning restore 612, 618
        }
    }
}
